# Generated by Django 3.2 on 2022-07-20 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=70)),
                ('phno', models.CharField(max_length=20)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('date_of_birth', models.DateField(verbose_name='DOB')),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('user_type', models.CharField(choices=[('Admin', 'Admin'), ('Shopuser', 'Shopuser'), ('Customer', 'Customer')], max_length=70)),
                ('creation_date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
