# Generated by Django 3.2 on 2022-07-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='date_of_birth',
            field=models.DateField(blank=True, verbose_name='DOB'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Shopuser', 'Shopuser'), ('Customer', 'Customer')], default='Customer', max_length=70),
        ),
    ]
