# Generated by Django 3.2 on 2022-07-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_accounts_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
