# Generated by Django 3.2 on 2022-07-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20220720_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accounts',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
